from .CPP14Lexer import CPP14Lexer
from .CPP14Parser import CPP14Parser
from antlr4 import Token

EXCLUDED_TOKEN_TYPES = {
    # Punctuation that does not contribute to structural similarity
    CPP14Lexer.LeftParen,
    CPP14Lexer.RightParen,
    CPP14Lexer.LeftBrace,
    CPP14Lexer.RightBrace,
    CPP14Lexer.Colon,
    CPP14Lexer.Comma,
    CPP14Lexer.Semi,
    CPP14Lexer.Identifier,
    # Keywords that do not contribute to structural similarity
    CPP14Lexer.Using,
    CPP14Lexer.Namespace,
    CPP14Lexer.Template,
    CPP14Lexer.Struct,
    CPP14Lexer.Public,
    CPP14Lexer.Private,
    CPP14Lexer.Protected,
    CPP14Lexer.Virtual,
    CPP14Lexer.Override,
    CPP14Lexer.Final,
    CPP14Lexer.Class,
    CPP14Lexer.Static,
    CPP14Lexer.Static_assert,
    CPP14Lexer.Inline,
    CPP14Lexer.Const,
    CPP14Lexer.Volatile,
    CPP14Lexer.Mutable,
    CPP14Lexer.Extern,
    CPP14Lexer.Register,
    CPP14Lexer.Friend,
    CPP14Lexer.Explicit,
    CPP14Lexer.Auto,
    CPP14Lexer.Decltype,
    CPP14Lexer.Typeid_,
    CPP14Lexer.Typename_,
    CPP14Lexer.Signed,
    CPP14Lexer.Unsigned,
    CPP14Lexer.New,
    CPP14Lexer.This,
    CPP14Lexer.True_,
    CPP14Lexer.False_,
    CPP14Lexer.Nullptr,
    CPP14Lexer.Operator,
    CPP14Lexer.Alignas,
    CPP14Lexer.Alignof,
    CPP14Lexer.Asm,
    CPP14Lexer.Goto,
    CPP14Lexer.Void,
    CPP14Lexer.Return,
    CPP14Lexer.Break,
    CPP14Lexer.Continue,
    # Keywords related to control flow
    CPP14Lexer.If,
    CPP14Lexer.Else,
    CPP14Lexer.For,
    CPP14Lexer.While,
    CPP14Lexer.Do,
    CPP14Lexer.Switch,
    CPP14Lexer.Case,
    CPP14Lexer.Default,
    CPP14Lexer.Try,
    CPP14Lexer.Catch,
    CPP14Lexer.Throw,
    # Keywords related to data types
    CPP14Lexer.Int,
    CPP14Lexer.Bool,
    CPP14Lexer.BinaryLiteral,
    CPP14Lexer.Char,
    CPP14Lexer.Double,
    CPP14Lexer.Float,
    CPP14Lexer.Long,
    CPP14Lexer.Short,
    CPP14Lexer.IntegerLiteral,
    CPP14Lexer.FloatingLiteral,
    CPP14Lexer.BooleanLiteral,
    CPP14Lexer.CharacterLiteral,
    CPP14Lexer.StringLiteral,
    # Whitespace and comments
    Token.EOF,
}
EXCLUDE_CHILDRENS_FROM_RULE = dict()
COLLAPSED_RULE_INDICES = {
    # Translation-unit and statement list wrappers
    CPP14Parser.RULE_declarationseq,
    CPP14Parser.RULE_statementSeq,
    # Common list wrappers
    CPP14Parser.RULE_expressionList,
    CPP14Parser.RULE_initializerList,
    CPP14Parser.RULE_parameterDeclarationClause,
    CPP14Parser.RULE_parameterDeclarationList,
    CPP14Parser.RULE_initDeclaratorList,
    CPP14Parser.RULE_baseSpecifierList,
    CPP14Parser.RULE_memberDeclaratorList,
    CPP14Parser.RULE_templateparameterList,
    CPP14Parser.RULE_templateArgumentList,
    CPP14Parser.RULE_typeIdList,
    CPP14Parser.RULE_attributeSpecifierSeq,
    CPP14Parser.RULE_attributeList,
    CPP14Parser.RULE_cvqualifierseq,
    # Declaration and namespace wrappers
    CPP14Parser.RULE_usingDirective,
    CPP14Parser.RULE_usingDeclaration,
    CPP14Parser.RULE_aliasDeclaration,
    CPP14Parser.RULE_templateDeclaration,
    CPP14Parser.RULE_namespaceDefinition,
    CPP14Parser.RULE_namespaceAliasDefinition,
    CPP14Parser.RULE_qualifiednamespacespecifier,
    # Declarator and initializer wrappers
    CPP14Parser.RULE_initDeclarator,
    CPP14Parser.RULE_noPointerDeclarator,
    CPP14Parser.RULE_noPointerNewDeclarator,
    CPP14Parser.RULE_parametersAndQualifiers,
    CPP14Parser.RULE_braceOrEqualInitializer,
}
HASHED_RULE_INDICES = set()
CONTROL_EQUIVALENCE_RULE_INDICES = dict()
EXCLUDED_RULE_TYPES = {
    # Identifier wrappers that only add depth once identifier tokens are excluded.
    CPP14Parser.RULE_unqualifiedId,
    CPP14Parser.RULE_declaratorid,
    CPP14Parser.RULE_className,
    CPP14Parser.RULE_templateName,
    CPP14Parser.RULE_originalNamespaceName,
}